package reminderapp;

import java.util.Date;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class Reminder extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    Statement st = null;
    
    public String titleE, contentE, timeE, dateE;
    
     // Creates new form Reminder
    public Reminder() {
        initComponents();
        
        conn = sqliteConnection.Connect();
        updateTable();
        
       addMouseListener(new PopupTriggerListener());
       dataTable.setComponentPopupMenu(RightClickPopupMenu);        // so the popup happens on rightclicking the table
       dataTable.addMouseListener(new PopupTriggerListener());
    }
    
    // code for SHOWING THE CONTENTS OF THE DB
     private void updateTable(){
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        String query = "select * from reminder0";
        try {
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

                while(rs.next()){
                    String title = rs.getString("Title");
                    String date = rs.getString("Date");
                    String time = rs.getString("Time");
                    String content = rs.getString("Content");
                     
                    Object[] row = { title, date, time, content };
                    model.addRow(row);
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
     
     
     // code for RIGHT CLICK
      class PopupTriggerListener extends MouseAdapter {
          
        public void mousePressed(MouseEvent ev) {
          if (ev.isPopupTrigger()) {
            RightClickPopupMenu.show(ev.getComponent(), ev.getX(), ev.getY());
          }

          // for getting data of the selected row of the table.
          Point point = ev.getPoint();
          int currentRow = dataTable.rowAtPoint(point);
          dataTable.setRowSelectionInterval(currentRow, currentRow);
          DefaultTableModel model = (DefaultTableModel) dataTable.getModel();

          String title, content, time, date;
          
          title = model.getValueAt(currentRow, 0).toString();
          date = model.getValueAt(currentRow, 1).toString();
          time = model.getValueAt(currentRow, 2).toString();
          content = model.getValueAt(currentRow, 3).toString();
          
          titleE = title;
          contentE = content;
          timeE = time;
          dateE = date;
          System.out.println(title +" - "+date +"- "+time +"- "+content);
        }

        public void mouseReleased(MouseEvent ev) {
          if (ev.isPopupTrigger()) {
             RightClickPopupMenu.show(ev.getComponent(), ev.getX(), ev.getY());
          }
        }

        public void mouseClicked(MouseEvent ev) {
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightClickPopupMenu = new javax.swing.JPopupMenu();
        Edit = new javax.swing.JMenuItem();
        DeleteAllPopup = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        NewReminderPopup = new javax.swing.JMenuItem();
        createDeleteDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDay = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxHour = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMinute = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxAmPm = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaContent = new javax.swing.JTextArea();
        SaveDialogButton = new javax.swing.JButton();
        CancelDialogButton = new javax.swing.JButton();
        AboutDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        CloseAboutDialog = new javax.swing.JButton();
        EditDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTitle1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxDay1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxMonth1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxYear1 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxHour1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxMinute1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxAmPm1 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaContent1 = new javax.swing.JTextArea();
        EditButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNew = new javax.swing.JMenuItem();
        jMenuDeleteAll = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuAboutApp = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuExit = new javax.swing.JMenuItem();

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        RightClickPopupMenu.add(Edit);

        DeleteAllPopup.setText("Delete All");
        DeleteAllPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllPopupActionPerformed(evt);
            }
        });
        RightClickPopupMenu.add(DeleteAllPopup);
        RightClickPopupMenu.add(jSeparator3);

        NewReminderPopup.setText("Add New");
        NewReminderPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewReminderPopupActionPerformed(evt);
            }
        });
        RightClickPopupMenu.add(NewReminderPopup);

        createDeleteDialog.setTitle("Create");
        createDeleteDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reminder Title"));

        jLabel1.setText("Title : ");

        jTextFieldTitle.setToolTipText("Enter Reminder Title");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        createDeleteDialog.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));

        jLabel2.setText("Day");

        jComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel3.setText("Month");

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel4.setText("Year");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        createDeleteDialog.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));
        jPanel3.setToolTipText("");

        jLabel5.setText("Hour");

        jComboBoxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel6.setText("Minute");

        jComboBoxMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        jLabel7.setText("AM/PM");

        jComboBoxAmPm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        createDeleteDialog.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Content"));

        jTextAreaContent.setColumns(20);
        jTextAreaContent.setRows(5);
        jScrollPane2.setViewportView(jTextAreaContent);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        createDeleteDialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 380, 110));

        SaveDialogButton.setText("Save");
        SaveDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDialogButtonActionPerformed(evt);
            }
        });
        createDeleteDialog.getContentPane().add(SaveDialogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        CancelDialogButton.setText("Cancel");
        CancelDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelDialogButtonActionPerformed(evt);
            }
        });
        createDeleteDialog.getContentPane().add(CancelDialogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        AboutDialog.setTitle("About");
        AboutDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Reminder v0.1");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        AboutDialog.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 60));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setText("This application lets you easily set reminders for any occation. You can Create, Edit, or Delete reminders. And has a user friendly interface.");
        jScrollPane4.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        AboutDialog.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 80));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane2.setText("PRODUCT VERSION : Reminder v0.1\nLanguage used : JAVA\n\nCreated by : Joju George.");
        jScrollPane3.setViewportView(jTextPane2);

        CloseAboutDialog.setText("Close");
        CloseAboutDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAboutDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(CloseAboutDialog)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseAboutDialog)
                .addContainerGap())
        );

        AboutDialog.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 380, 130));

        EditDialog.setTitle("Edit");
        EditDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Reminder Title"));

        jLabel9.setText("Title : ");

        jTextFieldTitle1.setEditable(false);
        jTextFieldTitle1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTitle1.setToolTipText("Enter Reminder Title");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        EditDialog.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 70));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));

        jLabel10.setText("Day");

        jComboBoxDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel11.setText("Month");

        jComboBoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel12.setText("Year");

        jComboBoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        EditDialog.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 70));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));
        jPanel10.setToolTipText("");

        jLabel13.setText("Hour");

        jComboBoxHour1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel14.setText("Minute");

        jComboBoxMinute1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        jLabel15.setText("AM/PM");

        jComboBoxAmPm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM", " " }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMinute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAmPm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxMinute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxAmPm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        EditDialog.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 70));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Content"));

        jTextAreaContent1.setColumns(20);
        jTextAreaContent1.setRows(5);
        jScrollPane5.setViewportView(jTextAreaContent1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        EditDialog.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 380, 110));

        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        EditDialog.getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        EditDialog.getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reminder");

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Date", "Month", "Content"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jMenu1.setText("File");

        jMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNew.setText("New Reminder");
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNew);

        jMenuDeleteAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuDeleteAll.setText("Delete All");
        jMenuDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeleteAllActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDeleteAll);
        jMenu1.add(jSeparator1);

        jMenuAboutApp.setText("About Application");
        jMenuAboutApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutAppActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAboutApp);
        jMenu1.add(jSeparator2);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //for SETTING DEFAULT VALUE IN CREATE/DELETE DIALOG BOX
    public void DefaultValues(){
        LocalDateTime now = LocalDateTime.now();
        Date d = new Date(); 
        String currentHour, currentMin, currentTimeStamp, currentDay, currentMonth, currentYear, title="", content="";
        
         currentHour = Integer.toString(now.getHour());
         currentMin = Integer.toString(now.getMinute());
         currentTimeStamp = new SimpleDateFormat("aa").format(d);
         currentDay = Integer.toString(now.getDayOfMonth());
         currentMonth = Integer.toString(now.getMonthValue());
         currentYear = Integer.toString(now.getYear());
        
         System.out.println(currentHour);
        jComboBoxHour.setSelectedItem(currentHour);
        jComboBoxMinute.setSelectedItem(currentMin);
        jComboBoxAmPm.setSelectedItem(currentTimeStamp);
        jComboBoxDay.setSelectedItem(currentDay);
        jComboBoxMonth.setSelectedItem(currentMonth);
        jComboBoxYear.setSelectedItem(currentYear);
        jTextFieldTitle.setText(title);
        jTextAreaContent.setText(content);
         }
    
    
    // function for DELETING ALL DB RECORDS
    public void DeleteAll(){
        // code for deleting
        String query = "delete from reminder0";
        try {
            st = conn.createStatement();
            st.executeUpdate(query);
                       
            // for refreshing the table.
            DefaultTableModel model=(DefaultTableModel) dataTable.getModel();
            while(model.getRowCount()>0){
                model.setRowCount(0);
            }
            updateTable();
                           
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, ex);
          }
    }
    
    
    // FILE MENU OPTIONS
    // on clicking ABOUT APP
    private void jMenuAboutAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutAppActionPerformed
        AboutDialog.setVisible(true);
        AboutDialog.setBounds(50, 50, 415, 340);
    }//GEN-LAST:event_jMenuAboutAppActionPerformed

    // on clicking NEW REMINDER
    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewActionPerformed
        createDeleteDialog.setVisible(true);
        createDeleteDialog.setBounds(150, 100, 420, 460);
        DefaultValues();
    }//GEN-LAST:event_jMenuNewActionPerformed

    // on clicking DELETE ALL
    private void jMenuDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeleteAllActionPerformed
        DeleteAll();
    }//GEN-LAST:event_jMenuDeleteAllActionPerformed

    // on clicking EXIT 
    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jMenuExitActionPerformed

    
    // function FOR SAVING THE DATA.
    public void Save(){
       //     try {
            String remTitle, remDay, remMonth, remYear, remHour, remMin, remAmPm, remContent;
            
            LocalDateTime now = LocalDateTime.now();
            Date d = new Date();
            
            String currentHour, currentMin, currentTimeStamp, currentDay, currentMonth, currentYear;
            
            currentHour = Integer.toString(now.getHour());
            currentMin = Integer.toString(now.getMinute());
            currentTimeStamp = new SimpleDateFormat("aa").format(d);
            currentDay = Integer.toString(now.getDayOfMonth());
            currentMonth = Integer.toString(now.getMonthValue());
            currentYear = Integer.toString(now.getYear());
            
            remTitle = jTextFieldTitle.getText();
            remDay = jComboBoxDay.getSelectedItem().toString();
            remMonth = jComboBoxMonth.getSelectedItem().toString();
            remYear = jComboBoxYear.getSelectedItem().toString();
            remHour = jComboBoxHour.getSelectedItem().toString();
            remMin = jComboBoxMinute.getSelectedItem().toString();
            remAmPm = jComboBoxAmPm.getSelectedItem().toString();
            remContent = jTextAreaContent.getText();
            
            String time = remHour+":"+remMin+" "+remAmPm;
           // DateFormat sdf = new SimpleDateFormat("HH:mm aa");
        //    Date t = sdf.parse(time);
            
            String dt = remDay+"-"+remMonth+"-"+remYear;
           // DateFormat sdf1 = new SimpleDateFormat("dd-MM-YYYY");
          //  Date date = sdf1.parse(dt);
            
            
            // for entering the correct date and time values
            if(currentHour.equals(remHour) && Integer.parseInt(currentMin) >= Integer.parseInt(remMin) && currentTimeStamp.equals(remAmPm) && currentDay.equals(remDay) && currentMonth.equals(remMonth) && currentYear.equals(remYear)){
                JOptionPane.showMessageDialog(null, "Enter correct Date and Time values please");
            }else if( !remTitle.isEmpty() && !remContent.isEmpty() ){
                
                // code for saving the input data into the database
                String query = "insert into reminder0 values('"+remTitle+"', '"+dt+"', '"+time+"', '"+remContent+"')";
                try {
                    st = conn.createStatement();
                    st.executeUpdate(query);
                       
                    // for refreshing the table.
                     DefaultTableModel model=(DefaultTableModel) dataTable.getModel();
                     while(model.getRowCount()>0){
                        model.setRowCount(0);
                    }
                     updateTable();
                     createDeleteDialog.setVisible(false);
                     createDeleteDialog.dispose();
                           
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }else {
                JOptionPane.showMessageDialog(null, "Fill all the fields");
            }
        
    //    } catch (ParseException ex) {
     //       Logger.getLogger(Reminder.class.getName()).log(Level.SEVERE, null, ex);
    //    }
    }
    
    //DIALOG BOX
    //on clicking SAVE BUTTON
    private void SaveDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDialogButtonActionPerformed
        Save();
    }//GEN-LAST:event_SaveDialogButtonActionPerformed

    //on clicking CANCEL BUTTON
    private void CancelDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelDialogButtonActionPerformed
        createDeleteDialog.setVisible(false);
        createDeleteDialog.dispose();
    }//GEN-LAST:event_CancelDialogButtonActionPerformed

    
    
    //MOUSE RIGHT CLICK POPUP MENU
    //on selecting the EDIT OPTION
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        try {
            EditDialog.setVisible(true);
            EditDialog.setBounds(150, 100, 420, 460);
            jTextFieldTitle1.setText(titleE);
            jTextAreaContent1.setText(contentE);
            
            String day, year, hour, min, timeStamp;
            int month;
            
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm aa");         
            SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
            
            Calendar c = Calendar.getInstance();
            c.setTime(sdf.parse(timeE));
            
            Calendar c1 = Calendar.getInstance();
            c1.setTime(sdf1.parse(dateE));
            
            System.out.println(c.get(Calendar.HOUR));
            Calendar c2 = Calendar.getInstance();
            
            day = String.valueOf(c1.get(Calendar.DAY_OF_MONTH));
            month = c1.get(Calendar.MONTH);
            year = String.valueOf(c1.get(Calendar.YEAR));
            hour = String.valueOf( c.get(Calendar.HOUR));
            min = String.valueOf(c.get(Calendar.MINUTE));
            timeStamp = String.valueOf(c.get(Calendar.AM_PM ));
            
            jComboBoxDay1.setSelectedItem(day);
            jComboBoxMonth1.setSelectedItem(String.valueOf(month));
            jComboBoxYear1.setSelectedItem(year);
            jComboBoxHour1.setSelectedItem(hour);
            jComboBoxMinute1.setSelectedItem(min);
            jComboBoxAmPm1.setSelectedItem(timeStamp);

        } catch (ParseException ex) {
            Logger.getLogger(Reminder.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_EditActionPerformed

    //on selecting the DELETE ALL OPTION
    private void DeleteAllPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllPopupActionPerformed
        DeleteAll();
    }//GEN-LAST:event_DeleteAllPopupActionPerformed
    
    //on selecting the NEW REMINDER OPTION
    private void NewReminderPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewReminderPopupActionPerformed
        createDeleteDialog.setVisible(true);
        createDeleteDialog.setBounds(150, 100, 420, 460);
        DefaultValues();
    }//GEN-LAST:event_NewReminderPopupActionPerformed

    
    // ABOUT DIALOG
    //on clicking  CLOSE BUTTON
    private void CloseAboutDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAboutDialogActionPerformed
       AboutDialog.setVisible(false);
       AboutDialog.dispose();
    }//GEN-LAST:event_CloseAboutDialogActionPerformed

    
    
    //EDIT DIALOG
    //on clicking EDIT BUTTON
    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        jTextFieldTitle1.setText(titleE);
        jTextAreaContent1.setText(contentE);
        
        String d,m,y,h,min,ts,cont;
        
        d = jComboBoxDay1.getSelectedItem().toString();
        m = jComboBoxMonth1.getSelectedItem().toString();
        y = jComboBoxYear1.getSelectedItem().toString();
        h = jComboBoxHour1.getSelectedItem().toString();
        min = jComboBoxMinute1.getSelectedItem().toString();
        ts = jComboBoxAmPm1.getSelectedItem().toString();
        cont = jTextAreaContent1.getText();
        
        System.out.println(cont);
        
        String date = d+"-"+m+"-"+y;
        String time = h+":"+min+" "+ts;

        
         String query = "update reminder0 set Date='"+date+"', Time='"+time+"', Content='"+cont+"' where Title='"+titleE+"'";
                try {
                    st = conn.createStatement();
                    st.executeUpdate(query);
                       
                    // for refreshing the table.
                     DefaultTableModel model=(DefaultTableModel) dataTable.getModel();
                     while(model.getRowCount()>0){
                        model.setRowCount(0);
                    }
                     updateTable();
                     createDeleteDialog.setVisible(false);
                     createDeleteDialog.dispose();
                           
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
                
      EditDialog.setVisible(false);
      EditDialog.dispose();                     
    }//GEN-LAST:event_EditButtonActionPerformed

    //on clicking CANCEL BUTTON
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        EditDialog.setVisible(false);
        EditDialog.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reminder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AboutDialog;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CancelDialogButton;
    private javax.swing.JButton CloseAboutDialog;
    private javax.swing.JMenuItem DeleteAllPopup;
    private javax.swing.JMenuItem Edit;
    private javax.swing.JButton EditButton;
    private javax.swing.JDialog EditDialog;
    private javax.swing.JMenuItem NewReminderPopup;
    private javax.swing.JPopupMenu RightClickPopupMenu;
    private javax.swing.JButton SaveDialogButton;
    private javax.swing.JDialog createDeleteDialog;
    private javax.swing.JTable dataTable;
    private javax.swing.JComboBox<String> jComboBoxAmPm;
    private javax.swing.JComboBox<String> jComboBoxAmPm1;
    private javax.swing.JComboBox<String> jComboBoxDay;
    private javax.swing.JComboBox<String> jComboBoxDay1;
    private javax.swing.JComboBox<String> jComboBoxHour;
    private javax.swing.JComboBox<String> jComboBoxHour1;
    private javax.swing.JComboBox<String> jComboBoxMinute;
    private javax.swing.JComboBox<String> jComboBoxMinute1;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxMonth1;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JComboBox<String> jComboBoxYear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAboutApp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDeleteAll;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextArea jTextAreaContent;
    private javax.swing.JTextArea jTextAreaContent1;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldTitle1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
